language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - bin/phing

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
